"""The prompt table is data, and these are the pins that keep it data.

Every digest below was computed from the frozen record's own expressions: the
donor scripts' literals, and for the two system prompts the donor's own f-string,
evaluated and compared byte for byte. A failure here is not a style regression.
It means a judged number in the record was taken under a different question than
the one this repository says it was taken under, and the number and the question
have come apart.
"""

from __future__ import annotations

import hashlib

import pytest

from anamnesis.judging import prompts as P

# ── The pins ──────────────────────────────────────────────────────────────────
SET_DIGESTS = {
    "analogical": "3cefa8130aea2516e9acff4c4fa96229bcf5e5f58a01e9d51c017e985b917554",
    "formality": "26aff2a129d6ad7c447cc619cb6fa0e58d3c9f0b22c13ea9a9d381a696b2c15d",
    "mode": "f3dc20c6da12e6e18d82cd98ca48089ef49efa73f92343edb7ecb01bf52b6312",
    "socratic": "c169c1481b0e9bf4aabba6eb51384fae6df2dbb7b519d95e9aae62c90a4c302c",
    "temperature": "f3003b17d3bd431e1c7a8b309dbe8b39488221b7390ecd5cdc344a4e8147dd23",
}

RUBRIC_DIGESTS = {
    "coherence": "6a18263a5336fff16dba9ad4d73454a904fd1257fb08c4b4da5a52882cd90868",
    "annex": "511eb415e13bed22c5c9ebcedb74806ee3864d40c833288765d5601c96630259",
    "likert_system": "58e2e711de16d2733e10535aa9f9df795a47a8fafe7fec7148d1b06d2b7fed4a",
}


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def test_every_prompt_set_matches_its_pinned_digest() -> None:
    assert set(P.PROMPT_SETS) == set(SET_DIGESTS)
    for name, digest in SET_DIGESTS.items():
        assert P.PROMPT_SETS[name].digest() == digest, f"{name} prompt text changed"


def test_the_shared_rubrics_match_their_pinned_digests() -> None:
    assert sha(P.COHERENCE_PROMPT) == RUBRIC_DIGESTS["coherence"]
    assert sha(P.ANNEX_TEMPLATE) == RUBRIC_DIGESTS["annex"]
    assert sha(P.likert_system_prompt()) == RUBRIC_DIGESTS["likert_system"]


def test_the_mode_system_prompt_is_the_donors_own_string() -> None:
    """Rebuilt here from the donor's expression, not from the ported template."""
    for mode, description in P.MODE_DESCRIPTIONS.items():
        theirs = (
            "You are an expert text analyst. You will be shown TWO texts (A and B) generated by a "
            "language model on the same topic. Exactly ONE was produced under an instruction to use "
            f"this processing mode:\n\n**{mode.capitalize()}**: {description}\n\n"
            "Decide which text follows that mode. Respond with ONLY a JSON object (no markdown "
            'fencing): {"choice": "A" or "B", "confidence": <1-5>}'
        )
        rendered = P.MODE.render(a="AAA", b="BBB", variant=mode, topic="T")
        assert rendered.system == theirs
        assert rendered.user == "Topic: T\n\n=== TEXT A ===\nAAA\n\n=== TEXT B ===\nBBB"


def test_the_temperature_system_prompt_is_the_donors_own_string() -> None:
    theirs = (
        "You are an expert text analyst. You will be shown TWO texts (A and B) generated by "
        "the same language model on the same topic, at DIFFERENT sampling temperatures. "
        f"Exactly ONE was {P.TEMPERATURE_DESCRIPTION}\n\nDecide which text (A or B) was produced at the "
        "higher temperature. Respond with ONLY a JSON object (no markdown fencing): "
        '{"choice": "A" or "B", "confidence": <1-5>}'
    )
    assert P.TEMPERATURE.render(a="a", b="b", variant="temperature", topic="T").system == theirs


def test_the_shift_prompt_is_the_donors_own_string() -> None:
    for mode, description in P.SHIFT_MODE_DESCRIPTIONS.items():
        theirs = f"""You will see two AI-generated texts, A and B, responding to similar prompts.

Which text is written in a MORE {mode.upper()} style? A {mode} text {description}.

Text A:
AAA

Text B:
BBB

Answer with exactly one letter: A or B."""
        rendered = P.SOCRATIC.render(a="AAA", b="BBB", variant=mode)
        assert rendered.user == theirs
        assert rendered.system is None


def test_the_two_mode_tables_are_different_instruments() -> None:
    """MODE and SOCRATIC ask about the same five modes in different words.

    They are two rows rather than one row with a flag because a win rate from one
    is not comparable with a win rate from the other: one asks which text followed
    an instruction, the other asks which text is more of a style.
    """
    assert set(P.MODE_DESCRIPTIONS) == set(P.SHIFT_MODE_DESCRIPTIONS)
    for mode in P.MODE_DESCRIPTIONS:
        assert P.MODE_DESCRIPTIONS[mode] != P.SHIFT_MODE_DESCRIPTIONS[mode]
    assert P.MODE.digest() != P.SOCRATIC.digest()


def test_every_set_carries_its_provenance() -> None:
    for name, prompt in P.PROMPT_SETS.items():
        assert prompt.name == name
        assert prompt.version == "v1"
        assert prompt.donor.startswith("anamnesis/scripts/"), name
        assert prompt.criterion_source, name
        assert prompt.axis, name


def test_the_json_sets_and_the_letter_sets_declare_their_parse() -> None:
    assert P.MODE.answer == "json_choice"
    assert P.TEMPERATURE.answer == "json_choice"
    for name in ("socratic", "analogical", "formality"):
        assert P.PROMPT_SETS[name].answer == "letter"


def test_variants_are_the_criteria_a_set_can_be_asked_for() -> None:
    assert P.MODE.variants() == tuple(sorted(P.MODE_DESCRIPTIONS))
    assert P.FORMALITY.variants() == ("formality",)
    assert P.ANALOGICAL.variants() == ("analogical",)


def test_a_set_refuses_a_variant_it_does_not_carry() -> None:
    with pytest.raises(P.PromptSetError, match="no variant"):
        P.MODE.render(a="a", b="b", variant="ironic", topic="T")
    with pytest.raises(P.PromptSetError, match="needs a variant"):
        P.MODE.render(a="a", b="b", topic="T")
    with pytest.raises(P.PromptSetError, match="carries its criterion inline"):
        P.FORMALITY.render(a="a", b="b", variant="socratic")


def test_a_set_that_renders_a_topic_refuses_to_render_without_one() -> None:
    with pytest.raises(P.PromptSetError, match="topic"):
        P.MODE.render(a="a", b="b", variant="linear")


def test_max_chars_truncates_both_sides_so_length_is_not_the_tell() -> None:
    rendered = P.FORMALITY.render(a="x" * 5000, b="y" * 10, max_chars=100)
    assert "x" * 100 in rendered.user
    assert "x" * 101 not in rendered.user


def test_braces_inside_a_text_are_not_reinterpreted() -> None:
    rendered = P.FORMALITY.render(a="{not_a_placeholder}", b="{b}")
    assert "{not_a_placeholder}" in rendered.user
    assert rendered.user.count("{b}") == 1


def test_the_digest_ignores_provenance_and_notices_a_word() -> None:
    same_text = P.FORMALITY.model_copy(update={"donor": "elsewhere.py"})
    assert same_text.digest() == P.FORMALITY.digest()
    reworded = P.FORMALITY.model_copy(
        update={"user_template": P.FORMALITY.user_template.replace("MORE FORMAL", "MORE formal")}
    )
    assert reworded.digest() != P.FORMALITY.digest()


def test_the_table_names_itself_on_a_miss() -> None:
    with pytest.raises(P.PromptSetError, match="the table holds"):
        P.prompt_set("register")


def test_the_likert_rubric_covers_the_five_modes_in_order() -> None:
    system = P.likert_system_prompt()
    assert tuple(P.JUDGE_MODE_DESCRIPTIONS) == P.VALID_MODES
    for i, mode in enumerate(P.VALID_MODES, 1):
        assert f"{i}. **{mode.title()}**" in system
    assert "which you do not know" in system
